// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_CustomStyle)
QT_DECLARE_EXTERN_RESOURCE(qmake_CustomStyle)
QT_DECLARE_EXTERN_RESOURCE(CustomStyle_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_CustomStyle)

class CustomStylePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    CustomStylePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_CustomStyle)
QT_KEEP_RESOURCE(qmlcache_CustomStyle)
QT_KEEP_RESOURCE(qmake_CustomStyle)
QT_KEEP_RESOURCE(CustomStyle_raw_qml_0)
    }
};



#include "CustomStyleplugin_CustomStylePlugin.moc"
